### ISSUE TITLE
test-simd fails on OSX with clang

### ISSUE THREAD

**Issue by ClementPernet** [linbox-team/fflas-ffpack#243]
See https://ci.inria.fr/linbox/job/FFLAS-FFPACK/Archi=linbox-osx,Compiler=clang++/431/PerfPublisher/testDetails.test-simd/

**Comment by cyrilbouvier** [comment]
The bug comes from the way I implemented the non-simd boolean operation (and, or, xor, andnot) for floating point types. Apparently, my usage of `reinterpret_cast` was not standard-compliant.
I tried to do something more compliant in commit 28cfb0c on the branch fix-test-simd-osx-clang. I am waiting to be able to test it on a OSX machine with clang before opening a PR.

**Comment by cyrilbouvier** [comment]
> @cyrilbouvier : you can use ssh to ci@linbox-osx.ci to connect to the osx box failing on our CI.

I tried but it asked me a password and i do not know which one is it (it tried my account password)

**Comment by cyrilbouvier** [comment]
I was able to access linbox-osx and test commit b8f9993. The test does not fail anymore.

The problem was not in the implementation of the non-simd boolean operation but in one function that performs the test. It is fixed by commit b8f9993.

**Comment by ClementPernet** [comment]
The pb is fixed.
