### ISSUE TITLE
fflas-ffpack cannot be configured with clang++ if Givaro was configured with g++

### ISSUE THREAD

**Issue by cyrilbouvier** [linbox-team/fflas-ffpack#244]
When givaro is configured with g++ (and maybe other compilers), the flag `-fabi-version=6` is set in `REQUIRED_FLAGS` and thus written in `givaro.pc`.

During configure of fflas-ffpack with clang++ (and maybe other compilers), it will be impossible to detect any BLAS library, thus the configure will fail.
Detection of BLAS is done with the macros `FF_CHECK_USER_BLAS` defined in `macros/fflas-ffpack-blas.m4`. Inside this macro, a small code is compiled using flags defined at line 60. Those flags contain `GIVARO_CFLAGS` (extracted from `givaro.pc` using `pkg-config`). So the small code will be compile with the flags `-fabi-version=6` which is not a valid flag for clang++, and the compilation will always fail, preventing configure to detect BLAS.

**Comment by ClementPernet** [comment]
Sure, this is, I think, the normal behaviour. (and I keep complaining about having to recompile givaro with clang whenever I want to test fflas-ffpack with clang.
The reason is that givaro, fflas and linbox are mostly source libraries, hence, fflas does not link to some binaries of givaro, but instead compiles the bits of givaro it requires.
The question is why do we need configure scripts then, who set such options as the fabi-version? 
I guess mostly to be able to compile the test benchmark  and example suites, and also to provide the user of the library with the right compile flags. 
In an ideal world, fflas-ffpack using givaro would not be considered as a normal user of givaro, but instead would trust its own configure script options to compile Givaro code.
This is an idea to be investigated further, in relation with #184 . Any volunteer to sort this mess out is welcome!

**Comment by cyrilbouvier** [comment]
Does pkg-config (or another tool) could provide a way to retrieve the compiler used to compile libgivaro ?
This would allow configure to abort sooner and with a clearer error message.


 > This is an idea to be investigated further, in relation with #184 . Any volunteer to sort this mess out is welcome!

A solution would be to regroup givaro, fflas and linbox into one repo and to have only one configure script for everything (with arguments to choose which library is compiled or not). But there may be issues that i do not see.

**Comment by ClementPernet** [comment]
> Does pkg-config (or another tool) could provide a way to retrieve the compiler used to compile libgivaro ?
I don't think so.
> This would allow configure to abort sooner and with a clearer error message.
> 
A hand made check (like does GIVARO_CFLAGS contains -fabi-version while I am compiling with clang) would do it, but that's not super fun.
 
> A solution would be to regroup givaro, fflas and linbox into one repo and to have only one configure script for everything (with arguments to choose which library is compiled or not). But there may be issues that i do not see.

I think the 3 libs are quite different in their scope, and have user different basis: someone only interested in the arithmetic of givaro should not bother download the whole linbox source, etc.
I would prefer keeping them separate.

**Comment by cyrilbouvier** [comment]
I proposed PR #247 for a better error message in this case.
