### ISSUE TITLE
README describes using './configure' but no such script exists

### ISSUE THREAD

**Issue by tumnus** [linbox-team/fflas-ffpack#338]
Hi, it seems as the the build process has moved on from the README.md

It describes using ./configure in the standard way, but there is no configure script in the repo
(I guess a comment about autogen.sh is needed?)

Thanks. Let me know if I can help out

**Comment by ClementPernet** [comment]
Hi,
Indeed, the use of configure script is intended towards the user installing the library from the released tar.gz file. If you are using it from the master branch of the git repo, you have to generate it using the script `autogen.sh`. We have added a feature forwarding arguments, so that you can pass to  autogen.sh the exact same arguments as the one you would pass to configure. I'll update the README.md file accordingly.
