### ISSUE TITLE
Illegal instruction on sparc64

### ISSUE THREAD

**Issue by d-torrance** [linbox-team/fflas-ffpack#342]
On the [sparc64 build of the 2.5.0rc0 package for Debian experimental](https://buildd.debian.org/status/fetch.php?pkg=fflas-ffpack&arch=sparc64&ver=2.5.0%7Erc0-1&stamp=1629820060&raw=0), all the tests fail, e.g.,:

```
../build-aux/test-driver: line 112: 367433 Illegal instruction     "$@" >> "$log_file" 2>&1
FAIL: test-fdot
```

It looks like some instruction set isn't available.  In previous versions, there were various `--disable-*` options to `configure` that could be used to disable instruction sets, but this feature appears to have been removed since the last release (I believe in #293).

**Comment by ClementPernet** [comment]
This is probably due to a compilation of the library on a different architecture than the one where the package has been tested on. By default we now pass `-march=native` option to the compiler. You can disable this by passing the `--without-archnative` option to the configure script.
Please let us know if it fixes the problem.

**Comment by d-torrance** [comment]
Yes, `--without-archnative` [did the trick on sparc64](https://buildd.debian.org/status/fetch.php?pkg=fflas-ffpack&arch=sparc64&ver=2.5.0%7Erc1-1&stamp=1638767321&raw=0) for the 2.5.0rc1 package in Debian experimental.  Thanks!
